[project]
name = "hydra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "daqh", email = "valeriodipasq@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "diffusers>=0.36.0",
    "fastjsonschema>=2.21.2",
    "hypernetx>=2.4.0",
    "rich>=14.3.2",
    "scikit-learn>=1.8.0",
    "tensorboardx>=2.6.4",
    "typer>=0.21.1",
    "xgi>=0.10",
]

[project.scripts]
hydra = "hydra.cli.main.app:main"
hydra-stats = "hydra.cli.stats.app:main"

[build-system]
requires = ["uv_build>=0.9.29,<0.10.0"]
build-backend = "uv_build"
